# Generated by Django 4.1 on 2025-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AYRA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/'),
        ),
    ]
